source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/artsy/Specs.git'


platform :ios, '8.0'
target ‘design’ do
    use_frameworks!
    pod 'AFNetworking', '~> 2.3.0'
    pod 'pop'
    pod 'YYModel'
    pod 'YYCache'
    pod 'YYImage'
    pod 'YYWebImage'
    pod 'YYText'
#    pod 'YYDispatchQueuePool'
    pod 'YYAsyncLayer'
    pod 'YYCategories'
    pod 'SVProgressHUD'
    pod 'SDWebImage'
    pod 'Reachability'
    pod 'Bugtags', '~> 2.2.2'
    pod 'MJRefresh'
    pod 'IQKeyboardManager'
    pod 'ReactiveObjC'
    pod 'Wonderful'
    pod 'Masonry'
    pod 'SDCycleScrollView'
    pod 'HMImagePicker'
    pod 'FMDB'
    pod 'Bugly'
    pod ‘BGDB_OC’, '~> 1.3’
    pod 'TMCache'
    pod 'OpenUDID', '~> 1.0.0'
  pod 'tingyunApp'
  pod 'FRDIntent', :git => 'https://github.com/douban/FRDIntent.git', :commit => '0.10.0'
#   pod 'JSLoadMoreService'
#    pod 'MLeaksFinder'
#    pod 'WCDB'
#    pod 'YYKeyboardManager'
#    pod 'UITableView+FDTemplateLayoutCell', '~> 1.5.beta'
#    pod 'FBMemoryProfiler'
#    pod 'LxGridView'
#    pod 'PromiseKit'
#    pod 'OMGHTTPURLRQ'
end

